"""Markdown content templates for Notion pages."""

from datetime import datetime


def incident_page_content(
    incident_id: str,
    title: str,
    severity: str,
    service: str,
    source: str,
    description: str,
    triggered_at: str,
    source_url: str = "",
    dashboard_url: str = "",
    runbook_url: str = "",
    labels: dict[str, str] | None = None,
) -> str:
    """Generate the initial Markdown content for an incident page."""
    links_section = ""
    if source_url:
        links_section += f"- [Alert Source]({source_url})\n"
    if dashboard_url:
        links_section += f"- [Dashboard]({dashboard_url})\n"
    if runbook_url:
        links_section += f"- [Runbook]({runbook_url})\n"

    labels_section = ""
    if labels:
        labels_section = "\n".join(f"- **{k}:** {v}" for k, v in labels.items())

    return f"""## Incident Details

**ID:** {incident_id}
**Severity:** {severity}
**Service:** {service}
**Source:** {source}
**Triggered:** {triggered_at}

### Description
{description}

### Links
{links_section if links_section else "_No links available_"}

### Labels
{labels_section if labels_section else "_No labels_"}

---

## Timeline
_Timeline events are added as comments on this page._

---

## Agent Analysis
_AI agents will post their analysis as comments below._
"""


def postmortem_content(
    incident_id: str,
    title: str,
    severity: str,
    service: str,
    duration: str,
    triggered_at: str,
    resolved_at: str,
    timeline_summary: str = "",
    root_cause: str = "",
    agent_analysis: str = "",
) -> str:
    """Generate postmortem page Markdown content."""
    return f"""## Incident Summary

| Field | Value |
|-------|-------|
| Incident ID | {incident_id} |
| Severity | {severity} |
| Service | {service} |
| Duration | {duration} |
| Triggered | {triggered_at} |
| Resolved | {resolved_at} |

### Customer Impact
_To be filled in during review._

---

## Timeline
{timeline_summary if timeline_summary else "_Reconstruct from incident page comments._"}

---

## Root Cause
{root_cause if root_cause else "_To be determined during postmortem review._"}

---

## What Went Well
- _To be filled in during review._

---

## What Could Be Improved
- _To be filled in during review._

---

## Action Items
- [ ] _Add specific, assignable action items._

---

## Lessons Learned
- _Key takeaways for the team._

---

*This postmortem was auto-generated by OpsLens. Please review and finalize.*
"""


def runbook_content(
    title: str,
    service: str,
    category: str,
    trigger_conditions: str,
    steps: list[str],
    rollback_steps: list[str] | None = None,
    notes: str = "",
) -> str:
    """Generate runbook page Markdown content."""
    steps_md = "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps))
    rollback_md = ""
    if rollback_steps:
        rollback_md = "## Rollback Procedure\n" + "\n".join(
            f"{i+1}. {step}" for i, step in enumerate(rollback_steps)
        )

    return f"""## Overview
**Service:** {service}
**Category:** {category}
**Trigger Conditions:** {trigger_conditions}

---

## Remediation Steps
{steps_md}

---

{rollback_md}

{f"## Notes{chr(10)}{notes}" if notes else ""}
"""
