apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opslens

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - opslens-deployment.yaml
  - celery-worker.yaml
  - celery-beat.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"

images:
  - name: ghcr.io/OWNER/opslens
    newTag: latest
