"""OpsLens observability stack: metrics, tracing, error tracking, and health checks."""

from src.observability.metrics import (
    MetricsMiddleware,
    metrics_endpoint,
    track_incident_created,
    track_agent_run,
    track_webhook,
    track_mcp_call,
    track_api_request,
    track_sla_breach,
    INCIDENTS_TOTAL,
    INCIDENTS_ACTIVE,
    INCIDENT_RESOLUTION_SECONDS,
    AGENT_DURATION_SECONDS,
    AGENT_CONFIDENCE,
    WEBHOOK_REQUESTS_TOTAL,
    WEBHOOK_LATENCY_SECONDS,
    MCP_REQUESTS_TOTAL,
    MCP_LATENCY_SECONDS,
    WS_CONNECTIONS,
    API_REQUESTS_TOTAL,
    API_LATENCY_SECONDS,
    DB_QUERY_SECONDS,
    CACHE_HITS,
    CACHE_MISSES,
    SLA_BREACHES_TOTAL,
    CIRCUIT_BREAKER_STATE,
    TASK_QUEUE_SIZE,
)
from src.observability.tracing import (
    setup_tracing,
    trace_agent_run as trace_agent_run_span,
    trace_mcp_call as trace_mcp_call_span,
    trace_webhook_processing,
    add_span_attributes,
    get_trace_id,
)
from src.observability.sentry_integration import (
    setup_sentry,
    capture_exception,
    capture_message,
    set_user_context,
    add_breadcrumb,
    SentryMiddleware,
)
from src.observability.health import (
    HealthChecker,
    HealthReport,
    CheckResult,
    setup_health_checks,
)

__all__ = [
    # Metrics
    "MetricsMiddleware",
    "metrics_endpoint",
    "track_incident_created",
    "track_agent_run",
    "track_webhook",
    "track_mcp_call",
    "track_api_request",
    "track_sla_breach",
    "INCIDENTS_TOTAL",
    "INCIDENTS_ACTIVE",
    "INCIDENT_RESOLUTION_SECONDS",
    "AGENT_DURATION_SECONDS",
    "AGENT_CONFIDENCE",
    "WEBHOOK_REQUESTS_TOTAL",
    "WEBHOOK_LATENCY_SECONDS",
    "MCP_REQUESTS_TOTAL",
    "MCP_LATENCY_SECONDS",
    "WS_CONNECTIONS",
    "API_REQUESTS_TOTAL",
    "API_LATENCY_SECONDS",
    "DB_QUERY_SECONDS",
    "CACHE_HITS",
    "CACHE_MISSES",
    "SLA_BREACHES_TOTAL",
    "CIRCUIT_BREAKER_STATE",
    "TASK_QUEUE_SIZE",
    # Tracing
    "setup_tracing",
    "trace_agent_run_span",
    "trace_mcp_call_span",
    "trace_webhook_processing",
    "add_span_attributes",
    "get_trace_id",
    # Sentry
    "setup_sentry",
    "capture_exception",
    "capture_message",
    "set_user_context",
    "add_breadcrumb",
    "SentryMiddleware",
    # Health
    "HealthChecker",
    "HealthReport",
    "CheckResult",
    "setup_health_checks",
]
